import "./hotel.css";
import Navbar from "../../components/navbar/Navbar";
import Header from "../../components/header/Header";
import Yurts from "../../assets/yurts.jpg";
import YurtInterior from "../../assets/yurtinterior.jpg";
import YurtInterior2 from "../../assets/yurtinterior2.jpg";
import YurtInterior3 from "../../assets/yurtinterior3.jpg";
import YurtExterior from "../../assets/yurtexterior.jpg";
import YurtExterior2 from "../../assets/yurtexterior2.jpg";

const Hotel = () => {
  const photos = [
    {
      src: { Yurts },
    },
    {
      src: { YurtExterior },
    },
    {
      src: { YurtExterior2 },
    },
    {
      src: { YurtInterior },
    },
    {
      src: { YurtInterior2 },
    },
    {
      src: { YurtInterior3 },
    },
  ];

  return (
    <div>
      <Navbar />
      <Header type="list" />
      <div className="hotelContainer">
        <div className="hotelWrapper">
          <h1 className="hotelTitle">Alaskan Wilderness Yurt</h1>
          <div className="hotelAddress">
            <div className="locationIcon">📍</div>
            <span>867 Jackawanda Rd. Seward, Alaska</span>
          </div>
          <span className="hotelDistance">15 miles from Airport</span>
          <span className="hotelPriceHighlight">
            For an addition $15 - local river fishing tour available
          </span>
          <div className="hotelImages">
            {photos.map((photo) => (
              <div className="hotelImgWrapper">
                <img src={photo.src} alt="" className="hotelImg" />
              </div>
            ))}
          </div>
              <div className="hotelDetails">
                {/* fix!!!!!!!!! */}
                <div className="hotelDetailsTexts">Explore the Alaskan Wilderness</div>
                <div className="hotelDetailsPrice">
                  Seward Alaskan is home is a spralling wilderness. 
                  There are local rivers and streams close
                  to the property along with trails for the hiking 
                  enthusists. The yurt rental comes with furnishings,
                  electricity generated by a gas powered generator. We advise
                  our guests to stock up on provisions in the local town 
                  prior to arriving. A refrigerator is provided in the yurt. 
                  This property is location 15 miles from the main airport and
                  an ATV ride from and to the airport is provided. Book an adventure 
                  of a life time! 
                </div>
              </div>

        </div>
      </div>
    </div>
  );
};

export default Hotel;
